name: kube-workflow

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  

jobs:
    kube-wf:
        runs-on: ubuntu-latest
        steps:
            - name: get identity
              uses: tremolosecurity/action-generate-oidc-jwt@v1.1
              with:
                audience:  https://k8sou.wfid.tremolo.dev/
                environmentVariableName: "JWT"

            - name: call kubernetes
              run: |
                export KUBECONFIG=$(mktemp)
                curl -H "Authorization: Bearer $JWT" https://k8sou.wfid.tremolo.dev/wftoken/token/user 2>/dev/null | jq -r '.token["kubectl Command"]' | sh
                kubectl get cm -n github-wf

